Set perms on rubygems credentials file
- Also makes all jobs serial

Fixes:
```
ERROR:  Your gem push credentials file located at:

/root/.gem/credentials

has file permissions of 0644 but 0600 is required.
```

[#136975857](https://www.pivotaltracker.com/story/show/136975857)

Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>